<div class="main-bottom" align="center">
	<?php
		if(isset($_GET['ac']))
		{
			if($_GET['ac']=='loaitin')
			{
				include("modules/loaitin/them.php");
				include("modules/loaitin/lietke.php");
			}
			if($_GET['ac']=='baiviet')
			{
				include("modules/baiviet/them.php");
				include("modules/baiviet/lietke.php");
			}
			if($_GET['ac']=='quangcao')
			{
				include("modules/quangcao/them.php");
				include("modules/quangcao/lietke.php");
			}
			if($_GET['ac']=='nguoidung')
			{
				include("modules/nguoidung/them.php");
				include("modules/nguoidung/lietke.php");
			}
		}
		if(isset($_GET['sua']))
		{
			if($_GET['sua']=='loaitin')
			{
				include("modules/loaitin/sua.php");
				include("modules/loaitin/lietke.php");
			}
			
			if($_GET['sua']=='baiviet')
			{
				include("modules/baiviet/sua.php");
				include("modules/baiviet/lietke.php");
			}
			if($_GET['sua']=='quangcao')
			{
				include("modules/quangcao/sua.php");
				include("modules/quangcao/lietke.php");
			}
			if($_GET['sua']=='nguoidung')
			{
				include("modules/nguoidung/sua.php");
				include("modules/nguoidung/lietke.php");
			}
		}
	?>
</div>